def htmlfy(input):
    try:
        input = input.decode('utf-8')
        input = input.replace("Á", "&Acute;")
        input = input.replace("á", "&aacute;")
        input = input.replace("À", "&Agrave;")
        input = input.replace("à", "&agrave;")
        input = input.replace("Â", "&Acirc;")
        input = input.replace("â", "&acirc;")
        input = input.replace("Ã", "&Atilde;")
        input = input.replace("ã", "&atilde;")
        input = input.replace("ç", "&ccedil;")
        input = input.replace("Ç", "&Ccedil;")
        input = input.replace("É", "&Eacute;")
        input = input.replace("é", "&eacute;")
        input = input.replace("È", "&Egrave;")
        input = input.replace("Ê", "&Ecirc;")
        input = input.replace("ê", "&ecirc;")
        input = input.replace("Í", "&Iacute;")
        input = input.replace("í", "&iacute;")
        input = input.replace("Ì", "&Igrave;")
        input = input.replace("ì", "&igrave;")
        input = input.replace("Ó", "&Oacute;")
        input = input.replace("ó", "&oacute;")
        input = input.replace("Õ", "&Otilde;")
        input = input.replace("õ", "&otilde;")
        return input.encode()
    except:
        return input
